### ISSUE TITLE
wine: Call from 0x7b43c6dc to unimplemented function api-ms-win-core-path-l1-1-0.dll.PathCchCanonicalizeEx, aborting

### ISSUE THREAD

**Issue by iver3on** [thawsystems/docker-wine-stable#3]
wine: Call from 0x7b43c6dc to unimplemented function api-ms-win-core-path-l1-1-0.dll.PathCchCanonicalizeEx, aborting

**Comment by Manouchehri** [comment]
Sorry, I think this is an issue with wine itself and not the container image. If that's not the case, let me know and I'll reopen the ticket! =)
